on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Run unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build Crews.Extensions.Primitives --configuration Release
    - name: Test
      run: dotnet test Crews.Extensions.Primitives.Tests --configuration Release