on:
  push:
    tags:
    - '**'
jobs:
  build:
    name: Publish NuGet package
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build Crews.Extensions.Primitives --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test Crews.Extensions.Primitives.Tests --configuration Release /p:Version=${VERSION}
    - name: Pack
      run: dotnet pack Crews.Extensions.Primitives --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push Crews.Extensions.Primitives.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}